# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'React', :path => '../node_modules/react-native'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

target 'naturalDisasters' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for naturalDisasters

  target 'naturalDisasters-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  end

  target 'naturalDisastersTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'naturalDisasters-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for naturalDisasters-tvOS

#   target 'naturalDisasters-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
